version: "3"

services:
  traefik-service:
    image: traefik:v2.3
    ports:
      # listen on port 80, default for http. necessary to redirect to https
      - 80:80
    volumes:
      # add docker as mounted volume, so that traefik can read the labels of other services
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      # enable docker in traefik, so that it reads labels form docker services
      - --providers.docker
      # donot expose all dokcer services, only the ones explicitly expose
      - --providers.docker.exposedbydefault=false
      # create an entrypoint "http" listening on port 80
      - --entrypoints.http.address=:80
      # enable the access log, with http requests
      - --accesslog
      #   enable the trafik log, for configurations and errors
      - --log
    networks:
      - traefik-public
    restart: always

networks:
  traefik-public:
    external: true
