version: "3"

services:
  fastapi-service:
    image: badlog/fastapi
    container_name: fastapi-server-container
    build:
      context: ./
    volumes:
      - ./src:/usr/app/src
    ports:
      - 8000:5000
    restart: always
